#!/usr/bin/env sh 
set -e
opt_zen="/opt/zen"
bin_zen="/usr/local/bin/zen"
zen_file="zen.linux-aarch64.tar.bz2"

update_browser() {
    if [ -f /usr/local/bin/browser.py ]; then
        python3 /usr/local/bin/browser.py 
        if [ -f "$opt_zen" ] || [ -f "$bin_zen" ]; then
            sudo rm -rf "$opt_zen" && sudo rm "$bin_zen"
            sudo tar xjf $zen_file -C /opt 
            sudo ln -s "$opt_zen/zen" "$bin_zen"
            exit 0

        else
            sudo tar xjf $zen_file -C /opt 
            sudo ln -s "$opt_zen/zen" "$bin_zen"
            exit 0
                
        fi  


    else 
        printf "Error: browser.py file not found"
        exit 1


    fi 
    

}

update_browser
